package top.sunbath.shared

val GREETING_POOL = listOf(
    "Hello, world!",
    "Hi there!",
    "Good morning!",
    "Greetings!",
    "Hey, how's it going?",
    "Good afternoon!",
    "Good evening!",
    "Howdy!",
    "What's up?",
    "Yo!",
    "Hiya!",
    "What's going on?",
    "Long time no see!",
    "Nice to meet you!",
    "How do you do?",
    "Hola!",
    "Bonjour!",
    "Ciao!",
    "Namaste!",
    "Saluton!",
    "Hallo!",
    "Konnichiwa!",
    "Aloha!",
    "Shalom!",
    "Salut!",
    "Sawubona!",
    "Goedendag!",
    "Boa tarde!",
    "G'day!",
    "Hello there!",
    "What's crackin'?",
    "How are you doing?",
    "What's happening?",
    "How's everything?",
    "How's life?",
    "How's it hanging?",
    "How's your day going?",
    "What's new?",
    "What's up, buttercup?",
    "What's the good word?",
    "Good to see you!",
    "How’s your week been?",
    "What’s cooking?",
    "How’s your day treating you?",
    "Hey there, sunshine!",
    "What's the vibe?",
    "How's it going, champ?",
    "How's life in the fast lane?",
    "How's everything on your side of the world?",
    "What's up, friend?",
    "How's your morning been?",
    "Are you doing well?",
    "How's your soul today?",
    "Nice to see you again!",
    "What's the story?",
    "Hello from the other side!",
    "How's the universe treating you?",
    "Is today a good day?",
    "Greetings, traveler!",
    "What brings you here?",
    "Hey, stranger!",
    "How’s the weather in your world?",
    "How’s your day so far?",
    "What’s the good news?",
    "Hey there, rockstar!",
    "Long time no chat!",
    "Nice to catch up!",
    "How’s the journey going?",
    "How are you feeling today?",
    "What's good?",
    "What’s the buzz?",
    "Hey, hey, hey!",
    "How’s life in the slow lane?",
    "Are you having a good day?",
    "What’s your mood today?",
    "What’s the plan for today?",
    "Got any fun plans today?",
    "Hope you're having an awesome day!",
    "Hey, you!",
    "How are you, my friend?",
    "How’s it going today?",
    "What’s the haps?",
    "What’s popping?",
    "Feeling good today?",
    "What’s the word on the street?",
    "Hey, you’ve got this!",
    "Hope you're doing well!",
    "Sending good vibes your way!",
    "How are you holding up?",
    "Any exciting news?",
    "What’s new and exciting?",
    "How’s life treating you today?",
    "What's on your mind?",
    "Got any cool plans?",
    "How's it going, pal?",
    "Hey, all the best!",
    "How are you today, buddy?",
    "What's up, homie?",
    "Everything cool?",
    "Yo, what's happening?",
    "How are you feeling today, superstar?",
    "I hope your day is going great!",
    "Hey there, pal!",
    "What’s good with you today?",
    "How's it going, mate?",
    "How’s the day shaping up?",
    "What’s going down?",
    "How’s the weather treating you?",
    "What’s cracking, dude?",
    "Feeling good today?"
)
