#Fri Jan 31 20:10:03 CST 2025
micronaut:
  application:
    name: helloworld
  security:
    enabled: true
    authentication: bearer
    endpoints:
      login:
        enabled: false
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_SECRET:pleaseChangeThisSecretForANewOne}
endpoints:
  health:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS
