#Fri Jan 31 20:10:03 CST 2025
micronaut:
  server:
    port: 8080
    # Set development environment context path
    # Because sam only simulates API Gateway v1 and passes the mapped base path to Lambda
    # Production environment uses API Gateway v2, HTTP API ($default) Lambda integration, API mapping
    # This does not pass the mapped path key to Lambda
    context-path: hello-world
