#Fri Jan 31 20:10:03 CST 2025
micronaut:
  server:
#    set context path for development.
#    because sam only simulates api gateway v1 and will pass mapped basepath to lambda.
#    production uses api gateway v2, http api ($default) lambda integration, api mappings,
#    which will not pass mapped path key to lambda.
    context-path: hello-world
