#Fri Jan 31 20:10:03 CST 2025
micronaut:
  server:
    cors:
      enabled: true
      allowed-origins:
        - '*'
      allowed-methods:
        - '*'
      allowed-headers:
        - '*'
# DynamoDB configuration
dynamodb:
  table-name: ${DYNAMODB_TABLE_NAME}
