#Fri Feb 28 04:15:00 CST 2025
micronaut:
  application:
    name: auth
  server:
    cors:
      enabled: true
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  security:
    enabled: false

endpoints:
  health:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS

netty:
  default:
    allocator:
      max-order: 3

# DynamoDB configuration
dynamodb:
  table-name: 'users'

aws:
  region: 'us-east-1'
  access-key-id: 'fake-key-id'
  secret-access-key: 'fake-access-key'

test-resources:
  containers:
    dynamodb:
      image-name: amazon/dynamodb-local
      hostnames:
        - dynamodb-local.host
      exposed-ports:
        - dynamodb-local.port: 8000
