#Fri Feb 28 04:15:00 CST 2025
micronaut:
  application:
    name: auth
  server:
    port: 8080
    # 设置开发环境的上下文路径
    # 因为 sam 只模拟 API Gateway v1，并将映射的基本路径传递给 Lambda
    # 生产环境使用 API Gateway v2，HTTP API ($default) Lambda 集成，API 映射
    # 这不会将映射的路径键传递给 Lambda
    context-path: auth

# 为了在本地开发环境中使用 DynamoDB，我们需要配置 DynamoDB 的端点
# 以及 AWS 认证信息
dynamodb-local:
  host: localhost
  port: 8000

dynamodb:
  table-name: users

aws:
  region: us-east-1
  access-key-id: fakeMyKeyId
  secret-access-key: fakeSecretAccessKey

# Resend configuration for development
resend:
  enabled: true
  api-key: ${RESEND_DEV_API_KEY}
