version: '3.8'

services:
  app:
    image: mcr.microsoft.com/devcontainers/base:ubuntu
    user: '${UID:-1000}:${GID:-1000}'
    volumes:
      # 项目文件映射
      - ..:/workspace:cached

      # 开发者身份和认证
      - ~/.ssh:/home/vscode/.ssh:cached # SSH 密钥和配置
      - ~/.config/gh:/home/vscode/.config/gh:cached # GitHub CLI 配置
      - ~/.aws:/home/vscode/.aws:cached # AWS 凭证和配置

      # 编辑器和IDE配置
      - ~/.cursor-server:/home/vscode/.cursor-server:cached
      - ~/.vscode-server:/home/vscode/.vscode-server:cached
      - ~/.vscode:/home/vscode/.vscode:cached
      - ~/vscode/.cache:/home/vscode/.cache:cached

      # 命令行体验优化
      - ~/.bash_history:/home/vscode/.bash_history:cached # Bash 历史记录
      - ~/.zsh_history:/home/vscode/.zsh_history:cached # Zsh 历史记录

      # 构建工具缓存
      - ~/.gradle:/home/vscode/.gradle:cached
      - ~/.m2:/home/vscode/.m2:cached

      # Node.js 包管理器缓存
      - ~/.pnpm-store:/home/vscode/.pnpm-store:cached
      - ~/.npm:/home/vscode/.npm:cached
      - ~/.cache/pnpm:/home/vscode/.cache/pnpm:cached
      - ~/.cache/typescript:/home/vscode/.cache/typescript:cached # TypeScript 编译缓存

    command: sleep infinity
    environment:
      - NODE_ENV=development
    ports:
      # Web 应用端口
      - '3000:3000' # API gateway
      - '5173:5173' # Vite dev
      - '4200:4200' # frontend svelte
      - '8080:8080' # backend micronaut
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
