version: '3.8'

services:
  app:
    image: mcr.microsoft.com/devcontainers/base:ubuntu
    volumes:
      - ..:/workspace:cached
      - ~/.cursor-server:/root/.cursor-server:cached
      - ~/.vscode-server:/root/.vscode-server:cached
      - ~/.vscode:/root/.vscode:cached
      - ~/.gradle:/root/.gradle:cached
      - ~/.m2:/root/.m2:cached
      - ~/.pnpm-store:/root/.pnpm-store:cached
      - ~/.npm:/root/.npm:cached
      - ~/.cache/pnpm:/root/.cache/pnpm:cached
    command: sleep infinity
    environment:
      - NODE_ENV=development
    ports:
      - '3000:3000'
      - '5173:5173'
      - '8080:8080'
    networks:
      - app-network
    extra_hosts:
      - 'host.docker.internal:host-gateway'

networks:
  app-network:
    driver: bridge
