name: CI build (lint and test)

on:
  pull_request:
    branches:
      - main

jobs:
  build-lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Fetch main branch
        run: |
          git fetch origin main --depth=1
          git branch -D main || true
          git branch --track main origin/main

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: |
          ./gradlew clean && pnpm nx affected:build --prod

      - name: Lint
        run: |
          pnpm nx affected:lint

      - name: Test
        run: |
          pnpm nx affected:test
